name: build QMK

on:
  - pull_request

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      QMK_VERSION: '0.22.14'
      PERSONAL_EMAIL: ${{ secrets.PERSONAL_EMAIL }}
      PERSONAL_EMAIL_DEV: ${{ secrets.PERSONAL_EMAIL_DEV }}
      WORK_EMAIL: ${{ secrets.WORK_EMAIL }}
    container:
      image: ghcr.io/qmk/qmk_cli:latest

    steps:
    - name: Checkout yusukemorita/keyball44_keymap
      uses: actions/checkout@v4

    - name: Cache qmk repository
      id: cache-qmk-repository
      uses: actions/cache@v4
      with:
        path: __qmk__
        key: qmk-${{ env.QMK_VERSION }}

    - name: Checkout qmk/qmk_firmware
      uses: actions/checkout@v4
      with:
        path: __qmk__
        repository: qmk/qmk_firmware
        submodules: recursive
        ref: ${{ env.QMK_VERSION }}

    - name: Setup QMK
      shell: bash
      run: qmk setup --home ./__qmk__ --yes

    - name: Install symbolic link
      run: ln -s $(pwd)/keyball __qmk__/keyboards/keyball

    - name: Compile
      run: qmk compile -kb keyball/keyball44 -km default -j 4

    - name: Upload built firmware to artifact
      id: artifact-upload
      uses: actions/upload-artifact@v4
      with:
        name: keyball44-firmware
        path: __qmk__/*.hex

    - name: Comment artifact url in PR
      uses: thollander/actions-comment-pull-request@v2
      with:
        message: |
          Compiled QMK firmware download URL: ${{ steps.artifact-upload.outputs.artifact-url }}
          Run: GITHUB_WORKFLOW_URL=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID