name: build trackpoint

on:
  pull_request:
    paths:
      - trackpoint/**
      - .github/workflows/build_trackpoint.yml

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: write # required for thollander/actions-comment-pull-request@v2
    env:
      QMK_VERSION: '0.27.1'
    container:
      image: ghcr.io/qmk/qmk_cli:latest

    steps:
    - name: Checkout yusukemorita/qmk_keymaps
      uses: actions/checkout@v4

    - name: Cache qmk repository
      id: cache-qmk-repository
      uses: actions/cache@v4
      with:
        path: __qmk__
        key: qmk-${{ env.QMK_VERSION }}

    - name: Checkout qmk/qmk_firmware
      uses: actions/checkout@v4
      with:
        path: __qmk__
        repository: qmk/qmk_firmware
        submodules: recursive
        ref: ${{ env.QMK_VERSION }}

    - name: Setup QMK
      shell: bash
      run: qmk setup --home ./__qmk__ --yes

    - name: Install symbolic link
      run: ln -s $(pwd)/trackpoint __qmk__/keyboards/trackpoint

    - name: Compile trackpoint
      run: qmk compile -kb trackpoint --keymap default

    - name: Upload firmware to artifacts
      id: firmware-upload
      uses: actions/upload-artifact@v4
      with:
        name: trackpoint-firmware
        path: __qmk__/*.hex

    - name: Comment artifact url in PR
      uses: thollander/actions-comment-pull-request@v2
      with:
        message: |
          Compiled trackpoint firmware download URL
          ${{ steps.firmware-upload.outputs.artifact-url }}

          Build URL
          ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
