name: build crkbd trackpoint

on:
  pull_request:
    paths:
      - crkbd-trackpoint/**
      - .github/workflows/build_crkbd_trackpoint.yml
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: write # required for thollander/actions-comment-pull-request@v2
    env:
      PERSONAL_EMAIL: ${{ github.sha }}
      PERSONAL_EMAIL_DEV: ${{ github.sha }}
      WORK_EMAIL: ${{ github.sha }}
      # PERSONAL_EMAIL: ${{ secrets.PERSONAL_EMAIL }}
      # PERSONAL_EMAIL_DEV: ${{ secrets.PERSONAL_EMAIL_DEV }}
      # WORK_EMAIL: ${{ secrets.WORK_EMAIL }}
    container:
      image: ghcr.io/qmk/qmk_cli:latest

    steps:
    - name: Checkout yusukemorita/qmk_keymaps
      uses: actions/checkout@v4

    - name: Checkout qmk/qmk_firmware
      uses: actions/checkout@v4
      with:
        path: __qmk__
        repository: holykeebs/qmk_firmware
        submodules: recursive
        ref: ce1df7cc236fcc6ce16d0d323cfe94a8c9315d86

    - name: Setup QMK
      shell: bash
      run: qmk setup --home ./__qmk__ --yes

    - name: Overwrite default keymaps and users directory
      run: |
        rm -rf __qmk__/keyboards/crkbd/keymaps/via
        cp -r crkbd-trackpoint/keymaps/via __qmk__/keyboards/crkbd/keymaps/

        rm -rf __qmk/users/holykeebs
        cp -r crkbd-trackpoint/users/holykeebs __qmk__/users/

    - name: Install python dependencies
      run: /usr/bin/python3 -m pip install -r /__w/qmk_keymaps/qmk_keymaps/__qmk__/requirements.txt

    - name: Compile crkbd-trackpoint
      run: make crkbd/rev1:via -e USER_NAME=holykeebs -e POINTING_DEVICE=trackpoint -e POINTING_DEVICE_POSITION=right
      working-directory: __qmk__

    - name: rename uf2 file
      run: mv __qmk__/crkbd_rev1_via.uf2 __qmk__/crkbd_rev1_via_${{ github.sha }}.uf2

    - name: Upload firmware to artifacts
      id: firmware-upload
      uses: actions/upload-artifact@v4
      with:
        name: crkbd-trackpoint-firmware
        path: __qmk__/*.uf2
        if-no-files-found: error

    - name: Comment artifact url in PR
      uses: thollander/actions-comment-pull-request@v2
      if: ${{ github.event_name == 'pull_request' }}
      with:
        message: |
          Compiled crkbd-trackpoint firmware download URL
          ${{ steps.firmware-upload.outputs.artifact-url }}

          Build URL
          ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
